services:
  tf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: 24.04
        AWSCLI_VERSION: 2.27.29
    container_name: aws
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - ./:/infrastructure
