# This script was generated by the AWS console with the "preview" option.
# It does NOT work!
# For the fixed version, check 01_create_vpc.sh

aws ec2 create-vpc --cidr-block "10.200.123.0/26" --instance-tenancy "default" --tag-specifications '{"resourceType":"vpc","tags":[{"key":"Name","value":"networking-bootcamp-vpc"}]}' 
aws ec2 modify-vpc-attribute --vpc-id "preview-vpc-1234" --enable-dns-hostnames '{"value":true}' 
aws ec2 describe-vpcs --vpc-ids "preview-vpc-1234" 
aws ec2 create-subnet --vpc-id "preview-vpc-1234" --cidr-block "10.200.123.0/28" --availability-zone "eu-central-1a" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"networking-bootcamp-subnet-public1-eu-central-1a"}]}' 
aws ec2 create-subnet --vpc-id "preview-vpc-1234" --cidr-block "10.200.123.32/28" --availability-zone "eu-central-1a" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"networking-bootcamp-subnet-private1-eu-central-1a"}]}' 
aws ec2 create-internet-gateway --tag-specifications '{"resourceType":"internet-gateway","tags":[{"key":"Name","value":"networking-bootcamp-igw"}]}' 
aws ec2 attach-internet-gateway --internet-gateway-id "preview-igw-1234" --vpc-id "preview-vpc-1234" 
aws ec2 create-route-table --vpc-id "preview-vpc-1234" --tag-specifications '{"resourceType":"route-table","tags":[{"key":"Name","value":"networking-bootcamp-rtb-public"}]}' 
aws ec2 create-route --route-table-id "preview-rtb-public-0" --destination-cidr-block "0.0.0.0/0" --gateway-id "preview-igw-1234" 
aws ec2 associate-route-table --route-table-id "preview-rtb-public-0" --subnet-id "preview-subnet-public-0" 
aws ec2 create-route-table --vpc-id "preview-vpc-1234" --tag-specifications '{"resourceType":"route-table","tags":[{"key":"Name","value":"networking-bootcamp-rtb-private1-eu-central-1a"}]}' 
aws ec2 associate-route-table --route-table-id "preview-rtb-private-1" --subnet-id "preview-subnet-private-1" 
aws ec2 describe-route-tables --route-table-ids  "preview-rtb-private-1" 